---
title: Course Communication
subtitle: ""
author: Andreas Handel
institute: "University of Georgia"
date: "`r file.mtime(knitr::current_input())`"
#bibliography: ../media/SMICourse.bib
output: 
  html_document:
    toc: FALSE
---



```{r, echo = FALSE}
#just so I can use emoticons
#devtools::install_github("hadley/emo")
library(emoji)
```


**We will be using both Slack and Zoom as described here.**


# Asynchronous communication

The main mode of communication will be through Slack. You should get an email invite to the Slack workspace for this class. It will be sent to the email you used to sign up for SISMID.

**Note that SISMID set up a Slack workspace for the whole summer institute, with a channel for each Module. We decided that it is better to have a separate workspace for this module, with our own channels. Thus, you will get invitations to 2 workspaces, the general SISMID one and the one for this module. Join both. If you have not gotten an email invite to our Slack workspace (which is called 2022-SISMID) the day before class starts, please let us know, either through the general SISMID Slack channel or by email, so we can make sure everyone is part of the workspace for our course.**

If you are unfamiliar with Slack, it is essentially a chat/discussion tool. Within the main workspace for this class, you will find different channels. That's the Slack name for a discussion forum. The names and descriptions of the different channels should be self-explanatory. You can also use Slack to send others direct messages.  

We will use the _**announcements**_ channel in our Slack workspace for important announcements, e.g., instructions how to join the Zoom calls, and any other important course communications. **You'll find a pinned message in that channel with details regarding Zoom calls.**

The other channels are for discussion of specific topics. The channel names should be self-explanatory. Use Slack widely to start discussions, ask questions, answer each others questions, notify us of things that are unclear/wrong, post links to interesting resources, network and socialize, etc. Hopefully we can use Slack to capture some of the in-class interactions that we can't have in an online course, and build a community of learners where you help and support each other. So please engage with each other and help each other. 

In general, it's better if you use Slack instead of Zoom chat or email to ask questions. If you use email, only you see the answer. For Zoom, once the session ends, the chat is gone. In Slack, others can see previous questions and answers. That said, there might be instances where the question only relates to you. In such cases, feel free to use email or send a direct message on Slack. 

While we try to monitor all all Slack channels in our workspace, things can get busy. If you asked a question and we didn't respond within a reasonable amount of time (a few hours during our workshop), feel free to ping us directly either by sending a direct message or by using the @ symbol in your slack message (e.g., @mikesmith will alert the user Mike Smith that he was mentioned in a message).

# Synchronous communication

We will have synchronous sessions through Zoom. Dates and times for Zoom meetings are listed in the __Schedule__ on this page. Those are subject to change. You can find the Zoom link in the _**announcements**_  Slack channel. We will also post any changes to the course schedule there. We plan to record the Zoom meetings and post those that are of general interest to the SMI site.




