---
title: SISMID 2022 Course Schedule
subtitle: ""
author: Andreas Handel
institute: "University of Georgia"
date: "`r file.mtime(knitr::current_input())`"
#bibliography: ../media/SMICourse.bib
output: 
  html_document:
    toc: FALSE
---

This is the schedule for the course. From here, you can access all instructions and materials to help you prepare. 

**This schedule is subject to change, so check regularly for updates. We will also adjust as needed, e.g. if we run over or end early, we just move breaks around. It's the same Zoom link for all meetings (see Slack for link).**


## Notes

* SISMID was online in 2020-2021 and we recorded our lectures. Instead of repeating the same lectures we gave previously, we figured you will get more out of the course if you watch (some of) our lectures from last year on your own time in advance, and then in our Zoom meetings we will just be emphasizing some of the highlights of our lectures, followed by discussion and Q&A time. **This only works if you actually watch the lectures. If not, you'll likely feel lost. You have been warned `r emoji::emoji('smile')`.**


* **Time zones:** Seattle is in the PT zone. Your instructors are in ET (Andreas) and CT (Paul) zones. Some of you are likely in yet other locations and time zones. We hope we can keep things straight. For any times in this course **we will use PT/Seattle time as reference.** We also plan to be clear when posting any time by stating the time zone explicitly. If ever in doubt, i.e. if you see us posting a time without specifying the zone, please tell us to clarify. 

* For details on Slack and Zoom use, see the __Communication__ section.

* Abbreviations used: [DSAIRM = Dynamical Systems Approach to Immune Response Modeling - R package](https://ahgroup.github.io/DSAIRM/). [SMI = Simulation Modeling in Immunology - website](https://andreashandel.github.io/SMIcourse/index.html). 




## Before course start

* Familiarize yourself with this website. Read through all of it.
* Post an Introduction to the _introductions-networking_ Slack channel. See the pinned post in that channel for instructions.
* Browse through our paper [Simulation Modelling for Immunologists](./media/2020-handel-natrevimm.pdf).
* Set up the tools needed for this course, namely R, Rstudio and the DSAIRM package. Instructions on how to do that can be found in the _**Software Setup**_ module of the [SMI site](https://andreashandel.github.io/SMIcourse).
* If you can, take a look at these apps in DSAIRM: __Basic Bacteria Model__ and __Basic Virus Model__. Play around with them and go through (some of) the tasks to get familiar with DSAIRM.


***


## Wednesday 2020-07-20, 11.30PT - 2.30PT

**As preparation before we meet, do the following:**

* Watch the __Introduction to Innate Immunity__ and __Introduction to Adaptive Immunity__ lecture recordings, which you can [find here](https://andreashandel.github.io/SMIcourse/Introduction_to_Immunology.html).

* Watch the __Introduction to Modeling__ and __Introduction to Simple Models__ lecture recordings, which you can [find here](https://andreashandel.github.io/SMIcourse/Introduction_to_Modeling.html). 

You are welcome to read start going through any other content on the SMI site prior to the start of the module.

***


11.30PT (1.30CT/2.30ET) - 12.15PT - Zoom: Welcome and introduction 

_break_

12.30PT (2.30CT/3.30ET) - 1.30PT  - Zoom: Introduction to immunology - highlights and discussion (Paul)

_break_

1.45PT (3.45CT/4.45ET) - 2.30PT  - Zoom: Introduction to modeling - highlights and discussion (Andreas)


Rest of day - On your own: Explore DSAIRM. Go through SMI materials. Prepare for tomorrow. Communication through Slack.  

***

## Thursday 2020-07-21, 8PT - 2.30PT

**As preparation before we meet, do the following:**

* Watch any of the lecture recordings on viral infections and immunology from the last years on the [SMI site](https://andreashandel.github.io/SMIcourse/). We will not repeat most of those topics this year, but we are happy to discuss any of those pathogens and topics in the Q&A, so if any of those viruses interest you, watch the lecture and come with questions for discussion, either during the Q&A or on Slack.  

* If you haven't already, take a look at the __Basic Bacteria Model__ and __Basic Virus Model__ apps in DSAIRM. Read the information describing the models and play around with them. If you want to continue, take a look at the __Acute Virus and IR Model__ and
__Chronic Virus and IR Model__ apps, which we'll be using today.


***

8PT (10CT/11ET) - 8.45PT - Zoom: Virology and immunology of acute viral infections (SARS-CoV-2, influenza, RSV)  (Paul)

_break_

9.00PT (11CT/12ET) - 9.30PT - Zoom: Discussion and Q&A of acute viral infections (Paul)

_break_

9.45PT (11.45CT/12.45ET) - 11.00PT - Zoom: Modeling acute viral infections with DSAIRM, level 1 (Andreas) 

11PT (1CT/2ET) - 12PT __Lunch Break__ - Go through SMI materials or explore DSAIRM on your own. Communication through Slack.  

12PT (2CT/3ET) - 12.45PT – Zoom: Virology and immunology of chronic viral infections (HIV, Herpes, HCV)  (Paul)

_break_

1.00PT (3CT/4ET) - 1.20PT – Zoom: Discussion and Q&A of chronic viral infections (Paul)

_break_

1.30PT (3.30CT/4.30ET) - 2.30PT - Zoom: Modeling chronic viral infections with DSAIRM, level 2 (Andreas)

Rest of day - On your own: Explore DSAIRM. Go through SMI materials. Prepare for tomorrow. Communication through Slack.  

***

## Friday 2020-07-22, 8PT - 2.30PT

**As preparation before we meet, do the following:**

* Go through the __Parameter Uncertainty__ unit on SMI, which you can [find here](https://andreashandel.github.io/SMIcourse/Parameter_Uncertainty_and_Sensitivity.html).

* Take a look at the __Extended Bacteria Model__ apps in DSAIRM, which we'll be exploring today. If you can, also take a brief look at the __Model Variant Exploration__ app, we'll do something similar with the bacteria model today. 

***

8PT (10CT/11ET) - 8.45PT - Zoom: Bacterial Infections and immunology (Tuberculosis, Streptococcus, Staphylococcus)  (Paul)

_break_

9.00PT (11CT/12ET) - 9.30PT - Zoom: Discussion and Q&A of bacterial infections (Paul)

_break_

9.45PT (11.45CT/12.45ET) - 11.00PT - Zoom: Modeling bacterial infections with DSAIRM, level 3 (Andreas)


11PT (1CT/2ET) - 12PT __Lunch Break__ - Go through SMI materials or explore DSAIRM on your own. Communication through Slack.  

_break_

12PT (2CT/3ET) - 1.45PT  – Zoom: Further immunology or modeling topics based on requests (Paul/Andreas) 

_break_

2PT (3.45CT/4.45ET) - 2.30PT  - Zoom: Final Q&A, course wrap-up (Paul/Andreas) 


***

## Any time

Go through any additional content on the [SMI website](https://andreashandel.github.io/SMIcourse/) that you are interested in. Explore the [DSAIRM models](https://ahgroup.github.io/DSAIRM/). Ask us questions about any of those topics on Slack.

***


## After course end

* This course website will remain online. It will not be further updated.
* The [SMI website](https://andreashandel.github.io/SMIcourse) is continuously online and will receive future updates as we produce more content.
* DSAIRM and modelbuilder packages will continue to be available.
* We will keep the Slack workspace open for at least several more weeks (but might be slower to respond). Feel free to keep using it. I'll post a note to the Slack workspace before I shut it down. If you want to continue communications with us or fellow classmates after that, we suggest you switch to other means (e.g., email).

